// <auto-generated />
namespace Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Champion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Champion));
        
        string IMigrationMetadata.Id
        {
            get { return "201304081445576_Champion"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
